import React from "react";
import {
  Award,
  BarChart3,
  Bell,
  Calendar,
  CalendarCheck,
  ChartNoAxesCombined,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleCheck,
  CircleHelp,
  ClipboardCheck,
  ClipboardList,
  Clock,
  CreditCard,
  Download,
  Dumbbell,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Flame,
  Gauge,
  Home,
  Info,
  KeyRound,
  LayoutDashboard,
  ListFilter,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MoreHorizontal,
  Pencil,
  Phone,
  Plus,
  QrCode,
  Receipt,
  ScanLine,
  Search,
  Settings,
  Share2,
  SlidersHorizontal,
  Star,
  Trash2,
  TrendingUp,
  User,
  UserPlus,
  Users,
  X,
} from "lucide-react";

const ICONS = {
  award: Award,
  barChart: BarChart3,
  bell: Bell,
  calendar: Calendar,
  calendarCheck: CalendarCheck,
  chart: ChartNoAxesCombined,
  check: Check,
  checkCircle: CircleCheck,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  clock: Clock,
  creditCard: CreditCard,
  download: Download,
  dumbbell: Dumbbell,
  eye: Eye,
  eyeOff: EyeOff,
  fileText: FileText,
  filter: Filter,
  flame: Flame,
  gauge: Gauge,
  home: Home,
  info: Info,
  key: KeyRound,
  grid: LayoutDashboard,
  listFilter: ListFilter,
  logOut: LogOut,
  mail: Mail,
  mapPin: MapPin,
  menu: Menu,
  more: MoreHorizontal,
  edit: Pencil,
  phone: Phone,
  plus: Plus,
  qrCode: QrCode,
  receipt: Receipt,
  scanLine: ScanLine,
  search: Search,
  settings: Settings,
  share: Share2,
  sliders: SlidersHorizontal,
  star: Star,
  trash: Trash2,
  trending: TrendingUp,
  user: User,
  userPlus: UserPlus,
  users: Users,
  x: X,
  help: CircleHelp,
  clipboardCheck: ClipboardCheck,
  clipboardList: ClipboardList,
};

const AppIcon = ({ name, size = 18, strokeWidth = 2, ...props }) => {
  const Icon = ICONS[name] || Info;
  return <Icon size={size} strokeWidth={strokeWidth} aria-hidden="true" {...props} />;
};

export default AppIcon;
